CREATE TABLE IF NOT EXISTS leads (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    website varchar(500),
    location varchar(200) NOT NULL,
    category varchar(100) NOT NULL,
    source varchar(100) NOT NULL DEFAULT 'manual',
    source_reference varchar(500),
    last_discovered_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS ix_leads_name_location
    ON leads (name, location);

CREATE TABLE IF NOT EXISTS signals (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id integer NOT NULL,
    has_promo boolean NOT NULL DEFAULT false,
    has_meta_ads boolean NOT NULL DEFAULT false,
    website_updated_recently boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT signals_lead_id_fkey
        FOREIGN KEY (lead_id)
        REFERENCES leads (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_signals_lead_id
    ON signals (lead_id);
