CREATE TABLE IF NOT EXISTS lead_insights (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id integer NOT NULL,
    signal_id integer NULL,
    trend_summary text NOT NULL DEFAULT '',
    score_snapshot integer NOT NULL,
    intent_level_snapshot varchar(20) NOT NULL,
    text text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT lead_insights_lead_id_fkey
        FOREIGN KEY (lead_id)
        REFERENCES leads (id)
        ON DELETE CASCADE,
    CONSTRAINT lead_insights_signal_id_fkey
        FOREIGN KEY (signal_id)
        REFERENCES signals (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_lead_insights_lead_id
    ON lead_insights (lead_id);

CREATE INDEX IF NOT EXISTS ix_lead_insights_created_at
    ON lead_insights (created_at);
