CREATE TABLE IF NOT EXISTS lead_actions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id integer NOT NULL,
    lead_insight_id integer NULL,
    action_type varchar(50) NOT NULL,
    title varchar(200) NOT NULL,
    description text NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'open',
    priority varchar(30) NOT NULL DEFAULT 'medium',
    created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
    completed_at timestamptz NULL,
    CONSTRAINT lead_actions_lead_id_fkey
        FOREIGN KEY (lead_id)
        REFERENCES leads (id)
        ON DELETE CASCADE,
    CONSTRAINT lead_actions_lead_insight_id_fkey
        FOREIGN KEY (lead_insight_id)
        REFERENCES lead_insights (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_lead_actions_lead_id
    ON lead_actions (lead_id);

CREATE INDEX IF NOT EXISTS ix_lead_actions_status
    ON lead_actions (status);
