CREATE TABLE IF NOT EXISTS lead_interactions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id integer NOT NULL,
    lead_action_id integer NULL,
    interaction_type varchar(50) NOT NULL,
    notes text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
    CONSTRAINT lead_interactions_lead_id_fkey
        FOREIGN KEY (lead_id)
        REFERENCES leads (id)
        ON DELETE CASCADE,
    CONSTRAINT lead_interactions_lead_action_id_fkey
        FOREIGN KEY (lead_action_id)
        REFERENCES lead_actions (id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_lead_interactions_lead_id
    ON lead_interactions (lead_id);

CREATE INDEX IF NOT EXISTS ix_lead_interactions_created_at
    ON lead_interactions (created_at);
