create table if not exists lead_signal_evidence (
    id bigint generated by default as identity primary key,
    lead_id integer not null references leads(id) on delete cascade,
    signal_id integer not null references signals(id) on delete cascade,
    channel varchar(40) not null,
    signal_type varchar(80) not null,
    source varchar(80) not null,
    confidence varchar(30) not null default 'weakly_inferred',
    weight integer not null default 0,
    reliability_multiplier numeric(6,4) not null default 1.0,
    freshness_multiplier numeric(6,4) not null default 1.0,
    effective_weight numeric(8,2) not null default 0,
    is_positive boolean not null default true,
    observed_at timestamptz,
    evidence_url text,
    value text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_lead_signal_evidence_lead_id
    on lead_signal_evidence (lead_id);

create index if not exists ix_lead_signal_evidence_signal_id
    on lead_signal_evidence (signal_id);

create index if not exists ix_lead_signal_evidence_lead_channel_created
    on lead_signal_evidence (lead_id, channel, created_at desc);

create unique index if not exists ux_lead_signal_evidence_signal_unique
    on lead_signal_evidence (signal_id, channel, signal_type, source, coalesce(evidence_url, ''), value);
