create table if not exists master_industry_strategy_profiles
(
    id uuid primary key default gen_random_uuid(),
    master_industry_id uuid not null unique references master_industries(id) on delete cascade,
    primary_persona text not null default '',
    buying_journey text not null default '',
    trust_sensitivity varchar(40) not null default '',
    default_language_biases_json jsonb not null default '[]'::jsonb,
    default_objective varchar(80) not null default '',
    funnel_shape varchar(80) not null default '',
    primary_kpis_json jsonb not null default '[]'::jsonb,
    sales_cycle varchar(80) not null default '',
    preferred_channels_json jsonb not null default '[]'::jsonb,
    base_budget_split_json jsonb not null default '{}'::jsonb,
    geography_bias varchar(80) not null default '',
    preferred_tone varchar(80) not null default '',
    messaging_angle text not null default '',
    recommended_cta text not null default '',
    proof_points_json jsonb not null default '[]'::jsonb,
    guardrails_json jsonb not null default '[]'::jsonb,
    restricted_claim_types_json jsonb not null default '[]'::jsonb,
    research_summary text not null default '',
    research_sources_json jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into master_industries (code, label)
values
    ('travel', 'Travel'),
    ('education', 'Education'),
    ('home_services', 'Home Services'),
    ('beauty', 'Beauty')
on conflict (code) do update
set
    label = excluded.label,
    updated_at = now();

insert into master_industry_aliases (master_industry_id, alias)
select industry.id, alias_rows.alias
from master_industries industry
cross join lateral (
    values
        ('travel'),
        ('tourism'),
        ('holiday'),
        ('vacation'),
        ('flights'),
        ('hotel'),
        ('accommodation')
) as alias_rows(alias)
where industry.code = 'travel'
on conflict (alias) do nothing;

insert into master_industry_aliases (master_industry_id, alias)
select industry.id, alias_rows.alias
from master_industries industry
cross join lateral (
    values
        ('education'),
        ('school'),
        ('college'),
        ('university'),
        ('training'),
        ('course'),
        ('academy')
) as alias_rows(alias)
where industry.code = 'education'
on conflict (alias) do nothing;

insert into master_industry_aliases (master_industry_id, alias)
select industry.id, alias_rows.alias
from master_industries industry
cross join lateral (
    values
        ('home services'),
        ('plumber'),
        ('electrician'),
        ('cleaning'),
        ('repairs'),
        ('maintenance'),
        ('contractor')
) as alias_rows(alias)
where industry.code = 'home_services'
on conflict (alias) do nothing;

insert into master_industry_aliases (master_industry_id, alias)
select industry.id, alias_rows.alias
from master_industries industry
cross join lateral (
    values
        ('beauty'),
        ('salon'),
        ('spa'),
        ('skincare'),
        ('cosmetics'),
        ('makeup'),
        ('aesthetics')
) as alias_rows(alias)
where industry.code = 'beauty'
on conflict (alias) do nothing;

insert into master_industry_strategy_profiles (
    master_industry_id,
    primary_persona,
    buying_journey,
    trust_sensitivity,
    default_language_biases_json,
    default_objective,
    funnel_shape,
    primary_kpis_json,
    sales_cycle,
    preferred_channels_json,
    base_budget_split_json,
    geography_bias,
    preferred_tone,
    messaging_angle,
    recommended_cta,
    proof_points_json,
    guardrails_json,
    restricted_claim_types_json,
    research_summary,
    research_sources_json
)
select
    industry.id,
    seeded.primary_persona,
    seeded.buying_journey,
    seeded.trust_sensitivity,
    seeded.default_language_biases_json::jsonb,
    seeded.default_objective,
    seeded.funnel_shape,
    seeded.primary_kpis_json::jsonb,
    seeded.sales_cycle,
    seeded.preferred_channels_json::jsonb,
    seeded.base_budget_split_json::jsonb,
    seeded.geography_bias,
    seeded.preferred_tone,
    seeded.messaging_angle,
    seeded.recommended_cta,
    seeded.proof_points_json::jsonb,
    seeded.guardrails_json::jsonb,
    seeded.restricted_claim_types_json::jsonb,
    seeded.research_summary,
    seeded.research_sources_json::jsonb
from master_industries industry
join (
    values
        (
            'retail',
            'Price-sensitive local shoppers comparing offers and nearby availability',
            'omnichannel exploration with strong store-visit intent',
            'medium',
            '["English"]',
            'promotion',
            'promotion-led',
            '["footfall","offer response","repeat visits"]',
            'short-response',
            '["OOH","Digital","Radio"]',
            '{"OOH":40,"Digital":35,"Radio":25}',
            'local-first',
            'performance',
            'local visibility, trusted value, and easy store action',
            'Visit us today',
            '["Highlight nearby availability and convenience.","Keep pricing or offer framing simple and clear.","Connect digital discovery to in-store action."]',
            '["Avoid inconsistent promotional claims across channels.","Keep store, stock, and offer details accurate.","Use clear local action cues."]',
            '[]',
            'Built around Google retail and omnichannel guidance showing the value of local inventory, store visits, and connected online-to-offline journeys.',
            '["https://www.thinkwithgoogle.com/intl/en-emea/consumer-insights/consumer-journey/how-omnichannel-insights-fuel-smarter-marketing-harveys-furniture/","https://www.thinkwithgoogle.com/_qs/documents/12597/How_to_boost_in-store_visits_this_holiday_season.pdf"]'
        ),
        (
            'automotive',
            'Vehicle shoppers comparing models, dealers, service options, and nearby availability',
            'research-heavy search journey that often ends in calls, directions, and dealer visits',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["qualified enquiries","test-drive bookings","dealer visits"]',
            'medium-consideration',
            '["Digital","OOH","Radio"]',
            '{"Digital":45,"OOH":35,"Radio":20}',
            'local-first',
            'balanced',
            'helpful, comparison-friendly guidance that moves shoppers toward action',
            'Book a test drive',
            '["Make dealer location and availability easy to find.","Support calls, directions, and appointment actions.","Use search-led creative for high-intent shoppers."]',
            '["Avoid vague pricing or stock claims.","Keep finance and offer details clear.","Make dealership contact options obvious."]',
            '[]',
            'Shaped by Google automotive research showing search, click-to-call, and directions as strong dealer-intent behaviors.',
            '["https://www.thinkwithgoogle.com/_qs/documents/1024/five-auto-shopping-moments-every-brand-must-own-final.pdf","https://www.thinkwithgoogle.com/intl/fr-fr/insights/parcours-consommateur/pourquoi-aider-le-client-en-amont-de-sa-visite-en-concession/"]'
        ),
        (
            'finance',
            'Consumers comparing rates, products, and providers while looking for clarity and trust',
            'digital-first evaluation with heavy cross-checking before conversion',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["qualified enquiries","application starts","cost per lead"]',
            'considered',
            '["Digital","Radio"]',
            '{"Digital":70,"Radio":30}',
            'balanced',
            'balanced',
            'clarity, trust, and useful guidance for high-consideration decisions',
            'Speak to an advisor',
            '["Lead with clarity, transparency, and usefulness.","Support comparison and research behavior.","Use trust markers before hard conversion asks."]',
            '["Avoid misleading rate or return claims.","Disclose product terms clearly.","Keep targeting and creative compliant with regulated-ad rules."]',
            '["consumer_finance_targeting_restrictions","misleading_financial_claims"]',
            'Anchored in Google finance journey research and official ad-policy restrictions for finance-related targeting and claims.',
            '["https://www.thinkwithgoogle.com/intl/en-apac/consumer-insights/consumer-journey/ai-search-finance-australia/","https://www.thinkwithgoogle.com/intl/fr-fr/strategies-marketing/tendances-de-recherche/le-search-premier-facteur-de-decision-du-parcours-finance/","https://support.google.com/adspolicy/answer/143465?hl=en","https://support.google.com/adspolicy/answer/2464998?hl=en"]'
        ),
        (
            'healthcare',
            'Nearby patients and families looking for accessible, trustworthy care',
            'high-intent local research with strong trust and compliance sensitivity',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["consultation intent","appointment bookings","qualified enquiries"]',
            'short-response',
            '["Digital","OOH","Radio"]',
            '{"Digital":55,"OOH":25,"Radio":20}',
            'local-first',
            'balanced',
            'credibility, safety, and clear next steps for nearby care',
            'Book a consultation',
            '["Lead with trust, accessibility, and clarity.","Make location and booking steps easy.","Support search-driven information needs."]',
            '["Avoid absolute treatment or outcome claims.","Only promote services allowed in the target market.","Ensure certifications or licensing requirements are met where required."]',
            '["treatment_guarantees","absolute_outcomes","restricted_healthcare_targeting"]',
            'Based on Google healthcare ad policies and the search-led behavior common to high-trust local service decisions.',
            '["https://support.google.com/adspolicy/answer/176031?guide=28435&hl=en","https://support.google.com/adspolicy/answer/143465?hl=en"]'
        ),
        (
            'real_estate',
            'Renters, buyers, sellers, and landlords evaluating nearby property opportunities',
            'research-led comparison journey with strong location relevance and regulated targeting limits',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["qualified enquiries","viewing requests","cost per lead"]',
            'considered',
            '["Digital","OOH"]',
            '{"Digital":70,"OOH":30}',
            'local-first',
            'balanced',
            'local market credibility, availability, and easy next-step action',
            'Book a viewing',
            '["Make location and property type clear.","Use trust and responsiveness before urgency.","Support map, contact, and viewing actions."]',
            '["Avoid discriminatory audience assumptions.","Keep listings and availability accurate.","Respect housing targeting restrictions on applicable ad platforms."]',
            '["housing_targeting_restrictions","discriminatory_targeting"]',
            'Grounded in official housing-targeting restrictions and local-service call behavior that matter for real-estate discovery.',
            '["https://support.google.com/adspolicy/answer/9997418?hl=en","https://support.google.com/adspolicy/answer/143465?hl=en","https://www.thinkwithgoogle.com/_qs/documents/1454/click-to-call_research-studies_hz2ytgv.pdf"]'
        ),
        (
            'travel',
            'Travellers moving from inspiration to comparison to confident booking',
            'multi-stage journey that blends inspiration, search research, and booking confidence',
            'medium',
            '["English"]',
            'leads',
            'consideration-led',
            '["booking enquiries","conversion rate","cost per acquisition"]',
            'mixed',
            '["Digital","OOH"]',
            '{"Digital":75,"OOH":25}',
            'balanced',
            'balanced',
            'confidence-building inspiration with clear booking action',
            'Plan your trip',
            '["Support inspiration and planning in the same journey.","Use helpful information to reduce booking friction.","Match creative to destination, trip type, or intent stage."]',
            '["Avoid vague price or availability claims.","Keep travel dates and conditions clear.","Reduce friction between research and booking."]',
            '[]',
            'Drawn from Google travel research showing the importance of search, video, confidence, and booking support across the journey.',
            '["https://www.thinkwithgoogle.com/intl/en-apac/marketing-strategies/automation/travel-advertising-ai-marketing/","https://www.thinkwithgoogle.com/intl/en-emea/marketing-strategies/video/how-youtube-creators-help-others-make-travel-decisions-virtually-experiencing-destinations-beforehand/","https://www.thinkwithgoogle.com/intl/en-apac/consumer-insights/consumer-trends/apac-travel-marketing-grow-brand/"]'
        ),
        (
            'education',
            'Prospective students and families comparing programs, outcomes, and affordability',
            'research-heavy path with high value on calls, guidance, and enrollment reassurance',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["qualified enquiries","application starts","enrollment conversions"]',
            'considered',
            '["Digital","Radio"]',
            '{"Digital":70,"Radio":30}',
            'balanced',
            'balanced',
            'supportive guidance that lowers friction in the enrollment journey',
            'Request information',
            '["Use strong guidance and reassurance for enrollment decisions.","Make calls and advisor contact easy.","Lead with program fit and outcome clarity."]',
            '["Avoid unverifiable outcome guarantees.","Keep accreditation or credential claims accurate.","Be precise about fees, timelines, and admissions steps."]',
            '["misleading_outcome_claims"]',
            'Shaped by Google education case studies and mobile click-to-call evidence tied to enrollment performance.',
            '["https://www.thinkwithgoogle.com/_qs/documents/1347/cunet-drives-quality-lead-volume-through-call-extension_case-studies.pdf","https://www.thinkwithgoogle.com/intl/fr-fr/futur-du-marketing/management-et-culture-d-entreprise/achats-b2b-nouveaux-profils-acheteurs/"]'
        ),
        (
            'home_services',
            'Homeowners and renters needing nearby providers they can contact quickly',
            'local search and call-led journey with strong urgency and trust needs',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["qualified enquiries","calls","booked jobs"]',
            'short-response',
            '["Digital","Radio","OOH"]',
            '{"Digital":60,"Radio":25,"OOH":15}',
            'local-first',
            'performance',
            'trusted local availability with clear service action',
            'Call now',
            '["Prioritize immediate contact paths.","Use local proof and service clarity.","Support urgent search behavior with fast-response CTAs."]',
            '["Avoid vague service-area promises.","Keep licensing and response-time claims accurate.","Make phone and local service coverage easy to verify."]',
            '[]',
            'Based on Google local-services guidance and click-to-call behavior research for local service categories.',
            '["https://support.google.com/google-ads/answer/6245891?hl=en","https://www.thinkwithgoogle.com/_qs/documents/1454/click-to-call_research-studies_hz2ytgv.pdf","https://www.thinkwithgoogle.com/intl/fr-fr/futur-du-marketing/transformation-digitale/stimuler-la-reprise-economique-grace-au-commerce/"]'
        ),
        (
            'food_hospitality',
            'Nearby diners and impulse-driven consumers deciding where to go right now',
            'quick, local, mobile-first journey influenced by convenience and visibility',
            'medium',
            '["English"]',
            'foot_traffic',
            'promotion-led',
            '["footfall","offer response","repeat visits"]',
            'short-response',
            '["OOH","Digital","Radio"]',
            '{"OOH":40,"Digital":40,"Radio":20}',
            'local-first',
            'high-visibility',
            'immediate relevance, convenience, and appetite appeal',
            'Visit today',
            '["Use local visibility and impulse cues.","Promote convenience, proximity, and social proof.","Keep offers and timing easy to understand."]',
            '["Avoid confusing operating hours or offer windows.","Keep menu, venue, and booking details accurate."]',
            '[]',
            'Built from local mobile click-to-call behavior and quick-turn journeys common to food and hospitality decisions.',
            '["https://www.thinkwithgoogle.com/intl/it-it/strategie/ricerca-google/il-ruolo-del-click-call-nel-processo-di-acquisto/","https://www.thinkwithgoogle.com/_qs/documents/11569/Journey_Reshaped-2020.pdf"]'
        ),
        (
            'beauty',
            'Beauty consumers seeking inspiration, reviews, and confidence before purchase or booking',
            'video and review-influenced journey spanning inspiration, comparison, and store or appointment action',
            'medium',
            '["English"]',
            'promotion',
            'consideration-led',
            '["store visits","booking intent","repeat purchase"]',
            'mixed',
            '["Digital","OOH"]',
            '{"Digital":80,"OOH":20}',
            'balanced',
            'balanced',
            'confidence, inspiration, and proof-led messaging for considered beauty choices',
            'Book now',
            '["Use reviews, demos, and visual proof.","Support both inspiration and immediate action.","Build trust before asking for conversion."]',
            '["Avoid unrealistic or misleading transformation claims.","Keep treatment or product claims evidence-based.","Align creative with service or product realities."]',
            '["misleading_cosmetic_claims"]',
            'Informed by Google beauty journey research showing strong roles for mobile discovery, reviews, and video inspiration.',
            '["https://www.thinkwithgoogle.com/intl/en-apac/future-of-marketing/digital-transformation/digital-makeover-how-sephora-measured-offline-impact-online-ads-singapore/","https://www.thinkwithgoogle.com/intl/de-de/insights/customer-journey/neue-kantar-studie-78-prozent-der-beauty-konsumentinnen-sind-nicht-loyal-gegenueber-nur-einer-marke/","https://www.thinkwithgoogle.com/intl/de-de/insights/customer-journey/auf-einen-kaffee-mit-ingrid-hochwind-und-stefan-hofmann-video-ist-das-praeferierte-format-f%C3%BCr-beauty-inspiration/"]'
        ),
        (
            'technology',
            'Decision-makers comparing tools, vendors, and implementation fit',
            'research and demo-led evaluation journey with higher information needs',
            'medium',
            '["English"]',
            'leads',
            'conversion-led',
            '["demo requests","qualified pipeline","cost per lead"]',
            'considered',
            '["Digital"]',
            '{"Digital":100}',
            'balanced',
            'balanced',
            'clarity, proof, and helpful evaluation support for complex decisions',
            'Book a demo',
            '["Lead with utility, proof, and fit.","Support comparison and research behavior.","Use direct response only after value is clear."]',
            '["Avoid vague capability claims.","Use clear proof, references, or demos to support messaging."]',
            '[]',
            'Aligned to B2B decision-making guidance where search, demos, and human support reduce friction in complex buying journeys.',
            '["https://www.thinkwithgoogle.com/intl/fr-fr/futur-du-marketing/management-et-culture-d-entreprise/achats-b2b-nouveaux-profils-acheteurs/"]'
        ),
        (
            'legal_services',
            'Individuals and businesses seeking clear next steps in stressful, high-trust legal moments',
            'search and response-led journey where confidence and professionalism matter early',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["qualified enquiries","consultation requests","response time"]',
            'short-response',
            '["Digital","Radio"]',
            '{"Digital":65,"Radio":35}',
            'local-first',
            'performance',
            'authority, clarity, and trustworthy response',
            'Request legal guidance',
            '["Lead with clarity and professionalism.","Make next-step contact simple.","Support urgent information needs with precise messaging."]',
            '["Avoid guaranteed case outcomes.","Do not overstate success certainty.","Keep claims precise and professional."]',
            '["guaranteed_case_outcomes","misleading_certainty"]',
            'Built from local-service call behavior and the compliance needs of high-trust professional services.',
            '["https://www.thinkwithgoogle.com/_qs/documents/1454/click-to-call_research-studies_hz2ytgv.pdf"]'
        ),
        (
            'funeral_services',
            'Families making urgent, emotionally sensitive decisions under pressure',
            'urgent local search with extremely high trust and tone sensitivity',
            'high',
            '["English"]',
            'leads',
            'conversion-led',
            '["qualified enquiries","call conversions","response time"]',
            'short-response',
            '["Digital","Radio","OOH"]',
            '{"Digital":45,"Radio":35,"OOH":20}',
            'local-first',
            'balanced',
            'dignity, trust, and immediate local support',
            'Speak to our team for guidance',
            '["Use compassionate, respectful support language.","Prioritize local availability and trust.","Make contact paths immediate and simple."]',
            '["Avoid aggressive urgency or discount framing.","Never use exploitative messaging.","Keep service claims factual and calm."]',
            '["aggressive_urgency","discount_pressure"]',
            'Designed for urgent local decision-making where trust, tone, and immediate access matter more than hard-sell promotion.',
            '["https://www.thinkwithgoogle.com/_qs/documents/1454/click-to-call_research-studies_hz2ytgv.pdf"]'
        ),
        (
            'general_services',
            'Local buyers comparing options and looking for a credible next step',
            'mixed local demand-capture journey with moderate consideration',
            'medium',
            '["English"]',
            'awareness',
            'balanced',
            '["reach","engagement","lead flow"]',
            'mixed',
            '["Digital","OOH","Radio"]',
            '{"Digital":50,"OOH":30,"Radio":20}',
            'local-first',
            'balanced',
            'visible, credible, and easy to act on',
            'Contact us to get started',
            '["Use clear local proof and easy next steps.","Keep messaging practical and trustworthy.","Balance awareness with action."]',
            '["Avoid vague claims that cannot be verified.","Keep local relevance and offer clarity high."]',
            '[]',
            'Acts as the generic local-services baseline when no stronger vertical strategy profile is available.',
            '["https://www.thinkwithgoogle.com/_qs/documents/1454/click-to-call_research-studies_hz2ytgv.pdf","https://www.thinkwithgoogle.com/intl/en-apac/consumer-insights/consumer-trends/purchase-journey-assistance/"]'
        )
) as seeded(
    industry_code,
    primary_persona,
    buying_journey,
    trust_sensitivity,
    default_language_biases_json,
    default_objective,
    funnel_shape,
    primary_kpis_json,
    sales_cycle,
    preferred_channels_json,
    base_budget_split_json,
    geography_bias,
    preferred_tone,
    messaging_angle,
    recommended_cta,
    proof_points_json,
    guardrails_json,
    restricted_claim_types_json,
    research_summary,
    research_sources_json
) on seeded.industry_code = industry.code
on conflict (master_industry_id) do update
set
    primary_persona = excluded.primary_persona,
    buying_journey = excluded.buying_journey,
    trust_sensitivity = excluded.trust_sensitivity,
    default_language_biases_json = excluded.default_language_biases_json,
    default_objective = excluded.default_objective,
    funnel_shape = excluded.funnel_shape,
    primary_kpis_json = excluded.primary_kpis_json,
    sales_cycle = excluded.sales_cycle,
    preferred_channels_json = excluded.preferred_channels_json,
    base_budget_split_json = excluded.base_budget_split_json,
    geography_bias = excluded.geography_bias,
    preferred_tone = excluded.preferred_tone,
    messaging_angle = excluded.messaging_angle,
    recommended_cta = excluded.recommended_cta,
    proof_points_json = excluded.proof_points_json,
    guardrails_json = excluded.guardrails_json,
    restricted_claim_types_json = excluded.restricted_claim_types_json,
    research_summary = excluded.research_summary,
    research_sources_json = excluded.research_sources_json,
    updated_at = now();
