import type { InventoryRow } from '../types/domain';

export const fallbackInventory: InventoryRow[] = [
  {
    id: 'inv-1',
    type: 'radio',
    station: 'Metro FM',
    region: 'Gauteng',
    language: 'English',
    showDaypart: 'Drive Time',
    timeBand: '15:00-18:00',
    slotType: '30 sec spot',
    duration: '30s',
    rate: 18500,
    restrictions: 'No alcohol after 17:00',
  },
  {
    id: 'inv-2',
    type: 'radio',
    station: 'Ukhozi FM',
    region: 'KwaZulu-Natal',
    language: 'Zulu',
    showDaypart: 'Breakfast',
    timeBand: '06:00-09:00',
    slotType: 'Live read',
    duration: '60s',
    rate: 12400,
    restrictions: 'Requires 48 hour script approval',
  },
  {
    id: 'inv-3',
    type: 'ooh',
    station: 'Sandton Digital Spectacular',
    region: 'Johannesburg',
    language: 'N/A',
    showDaypart: 'All day',
    timeBand: '00:00-23:59',
    slotType: 'Digital loop',
    duration: '10s',
    rate: 68000,
    restrictions: 'Creative ratio 16:9 only',
  },
  {
    id: 'inv-4',
    type: 'digital',
    station: 'Retail Mall Screens',
    region: 'Western Cape',
    language: 'English',
    showDaypart: 'Peak shopping',
    timeBand: '10:00-19:00',
    slotType: '15 sec screen slot',
    duration: '15s',
    rate: 24000,
    restrictions: 'Static creative only',
  },
];
