copy (
with outlet_languages as (
    select
        media_outlet_id,
        string_agg(language_code, '/' order by is_primary desc, language_code) as language_display
    from media_outlet_language
    group by media_outlet_id
),
outlet_keywords as (
    select
        media_outlet_id,
        string_agg(keyword, ' | ' order by keyword) as audience_keywords
    from media_outlet_keyword
    group by media_outlet_id
),
outlet_geo as (
    select
        media_outlet_id,
        max(province_code) filter (where geography_type = 'province') as province_code,
        max(city_name) filter (where geography_type = 'city') as city_name
    from media_outlet_geography
    group by media_outlet_id
)
select *
from (
    select
        concat('ooh_site:', iif.id::text) as inventory_key,
        'ooh' as channel,
        'site' as inventory_row_type,
        'inventory_items_final' as source_table,
        iif.id::text as source_id,
        'ooh' as source_type,
        null::text as outlet_code,
        coalesce(iif.supplier, iif.site_name, 'OOH site') as outlet_name,
        coalesce(iif.site_name, 'OOH site') as inventory_name,
        iif.media_type as media_subtype,
        null::text as package_name,
        null::text as slot_label,
        null::text as day_group,
        null::text as start_time,
        null::text as end_time,
        iif.province as province,
        iif.city as city,
        iif.suburb as suburb,
        coalesce(nullif(iif.suburb, ''), nullif(iif.city, ''), nullif(iif.province, '')) as area,
        rc.code as region_cluster_code,
        coalesce(iif.metadata_json ->> 'geography_scope', iif.province) as market_scope,
        null::text as coverage_type,
        null::text as market_tier,
        coalesce(iif.metadata_json ->> 'language', 'N/A') as language_display,
        null::text as language_notes,
        null::text as broadcast_frequency,
        nullif(iif.metadata_json ->> 'duration_seconds', '')::int as duration_seconds,
        coalesce(iif.metadata_json ->> 'slot_type', iif.media_type, 'placement') as rate_type,
        coalesce((iif.metadata_json ->> 'discounted_rate_zar')::numeric, (iif.metadata_json ->> 'rate_card_zar')::numeric, 0)::text as cost_zar,
        iif.metadata_json ->> 'rate_card_zar' as raw_rate_zar,
        null::text as investment_zar,
        null::text as cost_per_month_zar,
        null::text as value_zar,
        null::text as exposure_count,
        null::text as monthly_exposure_count,
        null::text as duration_weeks,
        null::text as duration_months,
        coalesce(nullif(iif.metadata_json ->> 'available', ''), 'true') as is_available,
        'false' as package_only,
        'false' as is_national,
        'true' as has_pricing,
        null::text as listenership_daily,
        null::text as listenership_weekly,
        null::text as listenership_period,
        null::text as existing_target_audience,
        null::text as existing_audience_age_skew,
        null::text as existing_audience_gender_skew,
        iif.metadata_json ->> 'lsm' as existing_audience_lsm_range,
        null::text as existing_audience_racial_skew,
        null::text as existing_urban_rural_mix,
        null::text as existing_audience_keywords,
        concat_ws(' | ',
            nullif(iif.metadata_json ->> 'traffic_count', ''),
            nullif(iif.metadata_json ->> 'dimensions', ''),
            nullif(iif.metadata_json ->> 'material', ''),
            nullif(iif.metadata_json ->> 'illuminated', ''),
            nullif(iif.address, '')
        ) as existing_source_notes,
        '' as enrich_target_audience,
        '' as enrich_audience_age_skew,
        '' as enrich_audience_gender_skew,
        '' as enrich_audience_lsm_range,
        '' as enrich_audience_racial_skew,
        '' as enrich_urban_rural_mix,
        '' as enrich_audience_keywords,
        '' as enrich_buying_behaviour_fit,
        '' as enrich_price_positioning_fit,
        '' as enrich_sales_model_fit,
        '' as enrich_objective_fit_primary,
        '' as enrich_objective_fit_secondary,
        '' as enrich_environment_type,
        '' as enrich_premium_mass_fit,
        '' as enrich_data_confidence,
        '' as enrich_notes
    from inventory_items_final iif
    left join region_clusters rc on rc.id = iif.region_cluster_id

    union all

    select
        concat('ooh_package:', mop.id::text) as inventory_key,
        'ooh' as channel,
        'package' as inventory_row_type,
        'media_outlet_pricing_package' as source_table,
        mop.id::text as source_id,
        'ooh_package' as source_type,
        mo.code as outlet_code,
        mo.name as outlet_name,
        concat(mo.name, ' - ', mop.package_name) as inventory_name,
        mop.package_type as media_subtype,
        mop.package_name as package_name,
        null::text as slot_label,
        null::text as day_group,
        null::text as start_time,
        null::text as end_time,
        og.province_code as province,
        og.city_name as city,
        null::text as suburb,
        coalesce(og.city_name, og.province_code, mo.coverage_type) as area,
        og.province_code as region_cluster_code,
        mo.coverage_type as market_scope,
        mo.coverage_type as coverage_type,
        mo.catalog_health as market_tier,
        coalesce(ol.language_display, 'N/A') as language_display,
        mo.language_notes,
        mo.broadcast_frequency,
        null::int as duration_seconds,
        'package' as rate_type,
        coalesce(mop.cost_per_month_zar, mop.investment_zar, mop.value_zar, 0)::text as cost_zar,
        null::text as raw_rate_zar,
        mop.investment_zar::text as investment_zar,
        mop.cost_per_month_zar::text as cost_per_month_zar,
        mop.value_zar::text as value_zar,
        mop.exposure_count::text as exposure_count,
        mop.monthly_exposure_count::text as monthly_exposure_count,
        mop.duration_weeks::text as duration_weeks,
        mop.duration_months::text as duration_months,
        mop.is_active::text as is_available,
        'true' as package_only,
        mo.is_national::text as is_national,
        mo.has_pricing::text as has_pricing,
        mo.listenership_daily::text as listenership_daily,
        mo.listenership_weekly::text as listenership_weekly,
        mo.listenership_period,
        mo.target_audience as existing_target_audience,
        mo.audience_age_skew as existing_audience_age_skew,
        mo.audience_gender_skew as existing_audience_gender_skew,
        mo.audience_lsm_range as existing_audience_lsm_range,
        mo.audience_racial_skew as existing_audience_racial_skew,
        mo.audience_urban_rural as existing_urban_rural_mix,
        ok.audience_keywords as existing_audience_keywords,
        concat_ws(' | ', mop.notes, mop.source_name, mop.source_date::text) as existing_source_notes,
        '' as enrich_target_audience,
        '' as enrich_audience_age_skew,
        '' as enrich_audience_gender_skew,
        '' as enrich_audience_lsm_range,
        '' as enrich_audience_racial_skew,
        '' as enrich_urban_rural_mix,
        '' as enrich_audience_keywords,
        '' as enrich_buying_behaviour_fit,
        '' as enrich_price_positioning_fit,
        '' as enrich_sales_model_fit,
        '' as enrich_objective_fit_primary,
        '' as enrich_objective_fit_secondary,
        '' as enrich_environment_type,
        '' as enrich_premium_mass_fit,
        '' as enrich_data_confidence,
        '' as enrich_notes
    from media_outlet_pricing_package mop
    join media_outlet mo on mo.id = mop.media_outlet_id
    left join outlet_languages ol on ol.media_outlet_id = mo.id
    left join outlet_keywords ok on ok.media_outlet_id = mo.id
    left join outlet_geo og on og.media_outlet_id = mo.id
    where lower(mo.media_type) = 'ooh'
      and mop.is_active = true

    union all

    select
        concat(lower(mo.media_type), '_package:', mop.id::text) as inventory_key,
        lower(mo.media_type) as channel,
        'package' as inventory_row_type,
        'media_outlet_pricing_package' as source_table,
        mop.id::text as source_id,
        concat(lower(mo.media_type), '_package') as source_type,
        mo.code as outlet_code,
        mo.name as outlet_name,
        concat(mo.name, ' - ', mop.package_name) as inventory_name,
        mop.package_type as media_subtype,
        mop.package_name as package_name,
        null::text as slot_label,
        null::text as day_group,
        null::text as start_time,
        null::text as end_time,
        og.province_code as province,
        og.city_name as city,
        null::text as suburb,
        coalesce(og.city_name, og.province_code, mo.coverage_type) as area,
        og.province_code as region_cluster_code,
        mo.coverage_type as market_scope,
        mo.coverage_type as coverage_type,
        mo.catalog_health as market_tier,
        coalesce(ol.language_display, 'N/A') as language_display,
        mo.language_notes,
        mo.broadcast_frequency,
        null::int as duration_seconds,
        'package' as rate_type,
        coalesce(mop.cost_per_month_zar, mop.investment_zar, mop.value_zar, 0)::text as cost_zar,
        null::text as raw_rate_zar,
        mop.investment_zar::text as investment_zar,
        mop.cost_per_month_zar::text as cost_per_month_zar,
        mop.value_zar::text as value_zar,
        mop.exposure_count::text as exposure_count,
        mop.monthly_exposure_count::text as monthly_exposure_count,
        mop.duration_weeks::text as duration_weeks,
        mop.duration_months::text as duration_months,
        mop.is_active::text as is_available,
        'true' as package_only,
        mo.is_national::text as is_national,
        mo.has_pricing::text as has_pricing,
        mo.listenership_daily::text as listenership_daily,
        mo.listenership_weekly::text as listenership_weekly,
        mo.listenership_period,
        mo.target_audience as existing_target_audience,
        mo.audience_age_skew as existing_audience_age_skew,
        mo.audience_gender_skew as existing_audience_gender_skew,
        mo.audience_lsm_range as existing_audience_lsm_range,
        mo.audience_racial_skew as existing_audience_racial_skew,
        mo.audience_urban_rural as existing_urban_rural_mix,
        ok.audience_keywords as existing_audience_keywords,
        concat_ws(' | ', mop.notes, mop.source_name, mop.source_date::text) as existing_source_notes,
        '' as enrich_target_audience,
        '' as enrich_audience_age_skew,
        '' as enrich_audience_gender_skew,
        '' as enrich_audience_lsm_range,
        '' as enrich_audience_racial_skew,
        '' as enrich_urban_rural_mix,
        '' as enrich_audience_keywords,
        '' as enrich_buying_behaviour_fit,
        '' as enrich_price_positioning_fit,
        '' as enrich_sales_model_fit,
        '' as enrich_objective_fit_primary,
        '' as enrich_objective_fit_secondary,
        '' as enrich_environment_type,
        '' as enrich_premium_mass_fit,
        '' as enrich_data_confidence,
        '' as enrich_notes
    from media_outlet_pricing_package mop
    join media_outlet mo on mo.id = mop.media_outlet_id
    left join outlet_languages ol on ol.media_outlet_id = mo.id
    left join outlet_keywords ok on ok.media_outlet_id = mo.id
    left join outlet_geo og on og.media_outlet_id = mo.id
    where lower(mo.media_type) in ('radio', 'tv')
      and mop.is_active = true

    union all

    select
        concat(lower(mo.media_type), '_slot:', msr.id::text) as inventory_key,
        lower(mo.media_type) as channel,
        'slot' as inventory_row_type,
        'media_outlet_slot_rate' as source_table,
        msr.id::text as source_id,
        concat(lower(mo.media_type), '_slot') as source_type,
        mo.code as outlet_code,
        mo.name as outlet_name,
        concat(mo.name, ' - ', to_char(msr.start_time, 'HH24:MI'), '-', to_char(msr.end_time, 'HH24:MI')) as inventory_name,
        msr.rate_type as media_subtype,
        null::text as package_name,
        concat(to_char(msr.start_time, 'HH24:MI'), '-', to_char(msr.end_time, 'HH24:MI')) as slot_label,
        msr.day_group,
        to_char(msr.start_time, 'HH24:MI') as start_time,
        to_char(msr.end_time, 'HH24:MI') as end_time,
        og.province_code as province,
        og.city_name as city,
        null::text as suburb,
        coalesce(og.city_name, og.province_code, mo.coverage_type) as area,
        og.province_code as region_cluster_code,
        mo.coverage_type as market_scope,
        mo.coverage_type as coverage_type,
        mo.catalog_health as market_tier,
        coalesce(ol.language_display, 'N/A') as language_display,
        mo.language_notes,
        mo.broadcast_frequency,
        msr.ad_duration_seconds as duration_seconds,
        msr.rate_type,
        msr.rate_zar::text as cost_zar,
        msr.rate_zar::text as raw_rate_zar,
        null::text as investment_zar,
        null::text as cost_per_month_zar,
        null::text as value_zar,
        null::text as exposure_count,
        null::text as monthly_exposure_count,
        null::text as duration_weeks,
        null::text as duration_months,
        msr.is_active::text as is_available,
        'false' as package_only,
        mo.is_national::text as is_national,
        mo.has_pricing::text as has_pricing,
        mo.listenership_daily::text as listenership_daily,
        mo.listenership_weekly::text as listenership_weekly,
        mo.listenership_period,
        mo.target_audience as existing_target_audience,
        mo.audience_age_skew as existing_audience_age_skew,
        mo.audience_gender_skew as existing_audience_gender_skew,
        mo.audience_lsm_range as existing_audience_lsm_range,
        mo.audience_racial_skew as existing_audience_racial_skew,
        mo.audience_urban_rural as existing_urban_rural_mix,
        ok.audience_keywords as existing_audience_keywords,
        concat_ws(' | ', msr.source_name, msr.source_date::text) as existing_source_notes,
        '' as enrich_target_audience,
        '' as enrich_audience_age_skew,
        '' as enrich_audience_gender_skew,
        '' as enrich_audience_lsm_range,
        '' as enrich_audience_racial_skew,
        '' as enrich_urban_rural_mix,
        '' as enrich_audience_keywords,
        '' as enrich_buying_behaviour_fit,
        '' as enrich_price_positioning_fit,
        '' as enrich_sales_model_fit,
        '' as enrich_objective_fit_primary,
        '' as enrich_objective_fit_secondary,
        '' as enrich_environment_type,
        '' as enrich_premium_mass_fit,
        '' as enrich_data_confidence,
        '' as enrich_notes
    from media_outlet_slot_rate msr
    join media_outlet mo on mo.id = msr.media_outlet_id
    left join outlet_languages ol on ol.media_outlet_id = mo.id
    left join outlet_keywords ok on ok.media_outlet_id = mo.id
    left join outlet_geo og on og.media_outlet_id = mo.id
    where lower(mo.media_type) in ('radio', 'tv')
      and msr.is_active = true
) inventory_export
order by channel, inventory_row_type, outlet_name, inventory_name
) to stdout with csv header;
